# Generated by Django 4.0.4 on 2022-05-21 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='disease',
            field=models.CharField(choices=[('BT', 'Brain Tumor'), ('L', 'Lukemia'), ('P', 'Pneumonia')], default='BT', max_length=2),
        ),
    ]
