# Generated by Django 4.0.4 on 2022-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_image_disease'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='caption',
        ),
        migrations.AlterField(
            model_name='image',
            name='disease',
            field=models.CharField(choices=[('bt', 'Brain Tumor'), ('l', 'Lukemia'), ('p', 'Pneumonia')], default='BT', max_length=2),
        ),
    ]
